### PR TITLE
Drop Python 3.5 support and modernize to Python 3.6+

### PR DESCRIPTION
**Pull request by eumiro**
- Drop Python 3.5 from GitHub Actions CI
- run `pyupgrade --py36-plus ankidroid`

### CODE REVIEW

**Comment by klieret** [comment]
Hi @eumiro . Thanks so much for improving code health with this and other PRs!  I'll come back to you in the next few days. As for dropping py3.5, there's two things:

* Let's add a quick catch to give a meaningful error message if people use py3.5
* What does semantic versioning say about the version number when we drop support for py3.5 ? (probably increase minor)

**Comment by eumiro** [comment]
According to https://stackoverflow.com/questions/26437467/is-there-a-standard-way-to-declare-old-python-versions-unsupported it is enough to define the minimum required Python version in `setup.py`, so I added it in the new commit.

And yes, I'd increase the minor version number.

**Comment by klieret** [comment]
Ah, right! Good point. But when people try to upgrade it will appear like there is no new version available then, right?

This is not so great. Then I'll release one last version for py3.5 before, which (when you run py3.5) says: There won't be any updates anymore.

**Comment by klieret** [comment]
basically like here: https://github.com/clusterking/clusterking/blob/master/clusterking/__init__.py

**Comment by eumiro** [comment]
> Ah, right! Good point. But when people try to upgrade it will appear like there is no new version available then, right?
> 
> This is not so great. Then I'll release one last version for py3.5 before, which (when you run py3.5) says: There won't be any updates anymore.

I like this approach to announce the deprecation. Then let's leave the PR here until you're ready and then I'll rebase it if needed.

**Comment by klieret** [comment]
@allcontributors please add @eumiro for code

**Pull request merged**
