### PR TITLE
Use the % style for log messages

### PR DESCRIPTION
**Pull request by eumiro**
See https://docs.python.org/3/howto/logging.html#logging-variable-data

### CODE REVIEW

**Comment by klieret** [comment]
The changes in this PR are now probably unnecessary, because f strings are the more elegant solution, right?  Hope you didn't spend too much time going through this!

**Comment by klieret** [comment]
I'll close this now for bookkeeping, feel free to reopen or comment.

**Comment by eumiro** [comment]
The linked documentation tells that the logs keep using the `%` format that is executed within the `logging` module. The main advantage is that comparing to the f-strings, `%` format is lazy, i.e. 

```python
log.debug(f'repr of big: {big!r}')
log.debug('repr of big: %r', big)
```

In the first case, the string will be always built (which may be expensive if the value's `repr` is bigger) even if the log level is set to info/warning/error and that debug would not be written anywhere. In the second case, the string will be evaluated only if the logger decides to do so. That's `'repr of big: %r', big` and not `'repr of big: %r' % (big,)` so the two arguments are passed independently.

It would be nice to have the choice in logging to use something like

```python
log.debug('repr of big: {!r}', big)
```

that would internally convert to `'repr of big: {!r}'.format(big)` if the logging level is enabled.

**Comment by eumiro** [comment]
@klieret as I mentioned, this `%` formatting in `logging` should not be replaced by `f-strings`, so please consider reopening and accepting this PR.

**Comment by eumiro** [comment]
I rebased and repushed my branch.

**Comment by klieret** [comment]
Hi @eumiro  Thanks for explaining the subtleties. Might not be too relevant for ankipandas, but since you did all the work, let's merge this :)   Can you open a new PR for that from your existing branch? Github is refusing to let me reopen this PR: "branch was force-pushed or recreated".

**Pull request closed without merging**
