### PR TITLE
docs: mention DocToolsLLM

### PR DESCRIPTION
**Pull request by thiswillbeyourgithub**
As asked there: https://github.com/klieret/AnkiPandas/issues/162#issuecomment-2164035088

Thanks a lot!

### CODE REVIEW

**Review by klieret — APPROVED** [review]

**Comment by thiswillbeyourgithub** [comment]
Hi! By complete chance I happened to stumbled upon the [page](https://ankipandas.readthedocs.io/en/latest/projects_with_ap.html) on your website and noticed that the page is not up to date with this commit.

So I decided to notify you because if it's not on purpose maybe there are other things that are outdated on it and you'd wanna know :)

Have a nice day!

**Comment by klieret** [comment]
Thanks! Will check on this soon!

**Comment by klieret** [comment]
Fixed :)

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot!

**Pull request merged**
